---
# 安装部署heketi

- name: 生成heketi服务使用的ssh管理密钥.
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    heketi_ssh_key_path: /root/heketi
  tasks:
    - name: 生成ssh密钥
      shell: |
        mkdir -p {{  heketi_ssh_key_path }}
        ssh-keygen -N '' -t rsa -q -f {{  heketi_ssh_key_path }}/private_key
      args:
        creates: "{{ heketi_ssh_key_path }}/private_key"

- name: 配置heketi ssh密钥认证
  hosts: glusterfs
  gather_facts: false
  vars:
    heketi_ssh_key_path: /root/heketi
  tasks: 
    - name: 传送heketi认证ssh密钥
      authorized_key:
        key: "{{ lookup('file', '{{ heketi_ssh_key_path }}/private_key.pub') }}" 
        state: present 
        user: root
    
    - name: Ensure ssh-rsa algorithm is allowed in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'PubkeyAcceptedAlgorithms=+ssh-rsa'
        state: present

    - name: Restart sshd service
      systemd:
        name: ssh
        state: restarted

- name: 安装部署heketi.
  hosts: glusterfs-node-0
  gather_facts: false
  vars:
    heketi_pkg:
      - heketi 
      - heketi-client
    heketi_server_port: "48080"
    heketi_admin_pass: "admin@P@ssW0rd"
    heketi_user_pass: "user@P@ssW0rd"
    heketi_devices: "/dev/nvme1n1"
    heketi_ssh_key_path: "/root/heketi"
    heketi_cli_server: "http://{{ hostvars['glusterfs-node-0']['ansible_ssh_host'] }}:48080"

    heketi_download_url: "https://github.com/heketi/heketi/releases/download/v10.4.0/heketi-v10.4.0-release-10.linux.amd64.tar.gz"
    heketi_version: "v10.4.0"

  tasks:
    - name: "Download Heketi"
      get_url:
        url: "{{ heketi_download_url }}"
        dest: "/tmp/heketi-{{ heketi_version }}.linux.amd64.tar.gz"

    - name: "Extract Heketi archive"
      unarchive:
        src: "/tmp/heketi-{{ heketi_version }}.linux.amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes
        
    - name: Copy Heketi binaries
      copy:
        src: "/tmp/heketi/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - heketi
        - heketi-cli   

    - name: Create Heketi directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /var/lib/heketi
        - /etc/heketi

    - name: Create Heketi config file
      template:
        src: heketi.json.j2
        dest: /etc/heketi/heketi.json
        backup: yes

    - name: Create Heketi service file
      template:
        src: heketi.service.j2
        dest: /lib/systemd/system/heketi.service
        backup: yes

    - name: "复制ssh-key-pub"
      copy:
        src: "{{ heketi_ssh_key_path }}/{{ item }}"
        dest: "/etc/heketi/"
        # group: heketi
        # owner: heketi
        mode: 0600
      with_items: 
        - private_key
        - private_key.pub

    - name: "启动并设置开机自动启动heketi服务"
      service:
        name: heketi
        state: restarted
        enabled: yes

    - name: "创建heketi文件-topology.json."
      template:
        src: topology.json.j2
        dest: /etc/heketi/topology.json
        backup: yes
    
    - name: "根据topology.json创建集群"
      shell: |
        heketi-cli --server {{ heketi_cli_server }} --user admin --secret {{ heketi_admin_pass }} topology load --json=/etc/heketi/topology.json

    - name: "配置heketi管理用环境变量"
      shell: |
        echo "alias heketi-cli='heketi-cli --server {{ heketi_cli_server }} --user admin --secret {{ heketi_admin_pass }}'" >> ~/.bashrc 

    # 后续的任务有待完善