---
# 初始化磁盘

- name: "初始化磁盘."
  hosts: servers
  gather_facts: false
  vars:
    data_disk: nvme1n1
    data_disk_num: 1
    data_disk_path: /var/lib/docker
  tasks:
    - name: "01-数据磁盘分区." 
      parted:
        device: /dev/{{ data_disk }} 
        number: "{{ data_disk_num }}" 
        state: present
      
    - name: "02-格式化数据磁盘."
      filesystem:
        dev: "/dev/{{ data_disk }}p{{ data_disk_num }}"
        fstype: xfs

    - name: "03-挂载数据盘."
      mount:
        path: "{{ data_disk_path }}"
        src: "/dev/{{ data_disk }}p{{ data_disk_num }}"
        fstype: xfs
        state: mounted
