---
# 初始化服务器

- name: 初始化服务器配置.
  hosts: servers
  gather_facts: false
  vars:
    host_upgrade: False
  tasks:
    - name: "01-停止并禁用ufw服务."
      service:
        name: ufw
        state: stopped
        enabled: no
      ignore_errors: True

    - name: "02-配置主机名."
      hostname:
        name: "{{ host_name }}"
    
    - name: "03-配置/etc/hosts."
      template:
        src: hosts.j2 
        dest: /etc/hosts

    - name: "04-配置时区."
      timezone:
        name: Asia/Shanghai

    # 升级操作系统并重启，默认不开启，自己根据需求开启   host_upgrade: True
    - name: "05-更新软件包列表."
      apt:
        update_cache: yes
      when: host_upgrade

    - name: "05-升级操作系统."
      apt:
        upgrade: dist
      register: upgrade
      when: host_upgrade

    - name: "05-升级操作系统后如果需要重启，则重启服务器."
      reboot:
        msg: "Rebooting to complete system upgrade"
        reboot_timeout: 900
      when:
        - host_upgrade
        - upgrade.changed


# - name: 06-配置时间同步.
#   include: deploy-chrony-client.yaml
